name: Publish npm package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com

    - name: Install dependencies
      run: npm ci

    - name: Run tests (optional)
      run: npm test

    - name: Publish package
      run: |
        npm version patch -m "Bump to version %s"
        npm publish --access public --scope=@boom-army
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
